<a href="https://colab.research.google.com/github/kikiru328/Bone_Detection/blob/main/%EA%B4%91%ED%9B%88/BA_TOTAL_RENAMED.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import cv2
import seaborn as sns
import os
%matplotlib inline

In [117]:
carpal_path = '/content/drive/MyDrive/2차 프로젝트 원본 데이터/crop_img/female/CARPAL'
carpal = os.listdir(carpal_path) 

ip_path = '/content/drive/MyDrive/2차 프로젝트 원본 데이터/crop_img/female/IP'
ip = os.listdir(ip_path)

lpip_path = '/content/drive/MyDrive/2차 프로젝트 원본 데이터/crop_img/female/LPIP'
lpip = os.listdir(lpip_path)

mpip_path = '/content/drive/MyDrive/2차 프로젝트 원본 데이터/crop_img/female/MPIP'
mpip = os.listdir(mpip_path)

LMCP_path = '/content/drive/MyDrive/2차 프로젝트 원본 데이터/crop_img/female/LMCP'
lmcp = os.listdir(LMCP_path)

MMCP_path = '/content/drive/MyDrive/2차 프로젝트 원본 데이터/crop_img/female/MMCP'
mmcp = os.listdir(MMCP_path)

TMCP_path = '/content/drive/MyDrive/2차 프로젝트 원본 데이터/crop_img/female/TMCP'
tmcp = os.listdir(TMCP_path)

In [126]:
F  = pd.DataFrame({'carpal':carpal,'lmcp':lmcp,'mmcp':mmcp,'tmcp':tmcp,'lpip':lpip,'mpip':mpip,'ip':ip})

In [127]:
F

           carpal          lmcp  ...          mpip            ip
0      1_F_cp.jpg    1_F_lm.jpg  ...    1_F_mp.jpg    1_F_ip.jpg
1      2_F_cp.jpg    2_F_lm.jpg  ...    2_F_mp.jpg    2_F_ip.jpg
2      3_F_cp.jpg    3_F_lm.jpg  ...    3_F_mp.jpg    3_F_ip.jpg
3      4_F_cp.jpg    4_F_lm.jpg  ...    4_F_mp.jpg    4_F_ip.jpg
4      5_F_cp.jpg    5_F_lm.jpg  ...    5_F_mp.jpg    5_F_ip.jpg
..            ...           ...  ...           ...           ...
566  568_F_cp.jpg  568_F_lm.jpg  ...  568_F_mp.jpg  568_F_ip.jpg
567  569_F_cp.jpg  569_F_lm.jpg  ...  569_F_mp.jpg  569_F_ip.jpg
568  570_F_cp.jpg  570_F_lm.jpg  ...  570_F_mp.jpg  570_F_ip.jpg
569  571_F_cp.jpg  571_F_lm.jpg  ...  571_F_mp.jpg  571_F_ip.jpg
570  572_F_cp.jpg  572_F_lm.jpg  ...  572_F_mp.jpg  572_F_ip.jpg

[571 rows x 7 columns]

In [ ]:
carpal_path = '/content/drive/MyDrive/2차 프로젝트 원본 데이터/crop_img/male/CARPAL'
carpal = os.listdir(carpal_path) 

ip_path = '/content/drive/MyDrive/2차 프로젝트 원본 데이터/crop_img/male/IP'
ip = os.listdir(ip_path)

lpip_path = '/content/drive/MyDrive/2차 프로젝트 원본 데이터/crop_img/male/LPIP'
lpip = os.listdir(lpip_path)

mpip_path = '/content/drive/MyDrive/2차 프로젝트 원본 데이터/crop_img/male/MPIP'
mpip = os.listdir(mpip_path)

LMCP_path = '/content/drive/MyDrive/2차 프로젝트 원본 데이터/crop_img/male/LMCP'
lmcp = os.listdir(LMCP_path)

MMCP_path = '/content/drive/MyDrive/2차 프로젝트 원본 데이터/crop_img/male/MMCP'
mmcp = os.listdir(MMCP_path)

TMCP_path = '/content/drive/MyDrive/2차 프로젝트 원본 데이터/crop_img/male/TMCP'
tmcp = os.listdir(TMCP_path)

In [ ]:
male = pd.DataFrame({'carpal':carpal,'lmcp':lmcp,'mmcp':mmcp,'tmcp':tmcp,'lpip':lpip,'mpip':mpip,'ip':ip})

In [168]:
with open('/content/drive/MyDrive/2차 프로젝트 원본 데이터/BA_all.pkl','rb') as file:
    all = pickle.load(file)

In [169]:
all

      No.  Group     등록번호  ...            ip gender  BA_zscore
0       1   1568  8110925  ...    1_F_ip.jpg      0  -1.591672
1       2    440  5988227  ...    2_F_ip.jpg      0  -1.966593
2       3   1724  8292016  ...    3_F_ip.jpg      0  -1.810376
3       4   1919  8565274  ...    4_F_ip.jpg      0  -1.841619
4       5   1264  7743478  ...    5_F_ip.jpg      0  -1.404211
...   ...    ...      ...  ...           ...    ...        ...
1231  661      9  3323383  ...  661_M_ip.jpg      1   1.720134
1232  662   1393  7893010  ...  662_M_ip.jpg      1   1.720134
1233  663    254  5900875  ...  663_M_ip.jpg      1   1.563916
1234  664   1431  7956005  ...  664_M_ip.jpg      1   1.845107
1235  665   1901  8542674  ...  665_M_ip.jpg      1   1.845107

[1236 rows x 24 columns]

In [174]:
all = all.rename(
    columns={
        'No.' : 'NO',
        '등록번호' : 'REGI',
        '진료의' : 'DCT_CODE',
        '생년월일' : 'BD',
        '처방일자' : 'PD',
        '시행일자' : 'OD',
        '검사 시 나이' : 'DIG_AGE',
        '신장' : 'HEIGT',
        '체중' : 'WEIGT',
        'Bone' : 'BONE',
        'BA 1' : 'BA_1',
        'BA 2' : 'BA_2',
        'carpal' : 'CARPAL',
        'lmcp' : 'LMCP',
        'mmcp' : 'MMCP',
        'tmcp' : 'TMCP',
        'lpip' : 'LPIP',
        'mpip' : 'MPIP',
        'ip' : 'IP'   }
)

In [175]:
all

       NO  gender  Group  ...          LPIP          MPIP            IP
0       1       0   1568  ...    1_F_lp.jpg    1_F_mp.jpg    1_F_ip.jpg
1       2       0    440  ...    2_F_lp.jpg    2_F_mp.jpg    2_F_ip.jpg
2       3       0   1724  ...    3_F_lp.jpg    3_F_mp.jpg    3_F_ip.jpg
3       4       0   1919  ...    4_F_lp.jpg    4_F_mp.jpg    4_F_ip.jpg
4       5       0   1264  ...    5_F_lp.jpg    5_F_mp.jpg    5_F_ip.jpg
...   ...     ...    ...  ...           ...           ...           ...
1231  661       1      9  ...  661_M_lp.jpg  661_M_mp.jpg  661_M_ip.jpg
1232  662       1   1393  ...  662_M_lp.jpg  662_M_mp.jpg  662_M_ip.jpg
1233  663       1    254  ...  663_M_lp.jpg  663_M_mp.jpg  663_M_ip.jpg
1234  664       1   1431  ...  664_M_lp.jpg  664_M_mp.jpg  664_M_ip.jpg
1235  665       1   1901  ...  665_M_lp.jpg  665_M_mp.jpg  665_M_ip.jpg

[1236 rows x 24 columns]

In [176]:
with open ('/content/drive/MyDrive/2차 프로젝트 원본 데이터/BA_all_.pkl','wb') as save:
    pickle.dump(all,save)

In [178]:
with open ('/content/drive/MyDrive/2차 프로젝트 원본 데이터/BA_all_.pkl','rb') as save:
    A = pickle.load(save)

In [179]:
A

       NO  gender  Group  ...          LPIP          MPIP            IP
0       1       0   1568  ...    1_F_lp.jpg    1_F_mp.jpg    1_F_ip.jpg
1       2       0    440  ...    2_F_lp.jpg    2_F_mp.jpg    2_F_ip.jpg
2       3       0   1724  ...    3_F_lp.jpg    3_F_mp.jpg    3_F_ip.jpg
3       4       0   1919  ...    4_F_lp.jpg    4_F_mp.jpg    4_F_ip.jpg
4       5       0   1264  ...    5_F_lp.jpg    5_F_mp.jpg    5_F_ip.jpg
...   ...     ...    ...  ...           ...           ...           ...
1231  661       1      9  ...  661_M_lp.jpg  661_M_mp.jpg  661_M_ip.jpg
1232  662       1   1393  ...  662_M_lp.jpg  662_M_mp.jpg  662_M_ip.jpg
1233  663       1    254  ...  663_M_lp.jpg  663_M_mp.jpg  663_M_ip.jpg
1234  664       1   1431  ...  664_M_lp.jpg  664_M_mp.jpg  664_M_ip.jpg
1235  665       1   1901  ...  665_M_lp.jpg  665_M_mp.jpg  665_M_ip.jpg

[1236 rows x 24 columns]